- id: xmaslights
  alias: xmaslights
  trigger:
  - platform: mqtt
    topic: "/HAwirelesslink/return/switch/xmaslights/state"
  action:
  - data:
      entity_id: switch.xmaslights
    service_template: >
      {% if trigger.payload == 'on' %}
        switch.turn_on
      {% else %} 
        switch.turn_off      
      {% endif %}
