- id: xmas_toggle
  alias: xmas_toggle
  trigger:
  - platform: mqtt
    topic: zwave/cafetera/set
  action:
  - data:
      entity_id: switch.main_bath_fan
    service_template: >
      {% if trigger.payload == 'on' %}
        switch.turn_on
      {% else %} 
        switch.turn_off      
