- id: xmaslights
  alias: xmaslights
  trigger:
  - platform: mqtt
    topic: "/HAwirelesslink/return/switch/xmaslights/state"
  action:
  - data:
      entity_id: switch.xmaslights
    service_template: >
      {% if trigger.payload == 'on' %}
        switch.turn_on
      {% else %} 
        switch.turn_off      
      {% endif %}

- id: linear_pd300z2_plugin_dimmer_module_level_brightness
  alias: linear_pd300z2_plugin_dimmer_module_level_brightness
  trigger:
  - platform: mqtt
    topic: "/HAwirelesslink/return/light/linear_pd300z2_plugin_dimmer_module_level/brightness"
  action:
  - data_template:
      entity_id: light.linear_pd300z2_plugin_dimmer_module_level
      brightness: "{{ trigger.payload | int }}"
    service_template: >
      {% if trigger.payload | int == 0 %}
        light.turn_off
      {% else %} 
        light.turn_on     
      {% endif %}       

- id: linear_pd300z2_plugin_dimmer_module_level
  alias: linear_pd300z2_plugin_dimmer_module_level
  trigger:
  - platform: mqtt
    topic: "/HAwirelesslink/return/light/linear_pd300z2_plugin_dimmer_module_level/state"
  action:
  - data:
      entity_id: light.linear_pd300z2_plugin_dimmer_module_level
    service_template: >
      {% if trigger.payload == 'on' %}
        light.turn_on
      {% else %} 
        light.turn_off      
      {% endif %}


- id: livingroom_entry_brightness
  alias: livingroom_entry_brightness
  trigger:
  - platform: mqtt
    topic: "/HAwirelesslink/return/light/livingroom_entry/brightness"
  action:
  - data_template:
      entity_id: light.leviton_dz6hd1bz_decora_600w_smart_dimmer_level
      brightness: "{{ trigger.payload | int }}"
    service_template: >
      {% if trigger.payload | int == 0 %}
        light.turn_off
      {% else %} 
        light.turn_on     
      {% endif %}       

- id: livingroom_entry
  alias: livingroom_entry
  trigger:
  - platform: mqtt
    topic: "/HAwirelesslink/return/light/livingroom_entry/state"
  action:
  - data:
      entity_id: light.leviton_dz6hd1bz_decora_600w_smart_dimmer_level
    service_template: >
      {% if trigger.payload == 'on' %}
        light.turn_on
      {% else %} 
        light.turn_off      
      {% endif %}
