- id: linear_pd300z2_plugin_dimmer_module_level_brightness
  alias: linear_pd300z2_plugin_dimmer_module_level_brightness
  trigger:
  - platform: mqtt
    topic: "/HAwirelesslink/return/light/linear_pd300z2_plugin_dimmer_module_level/brightness"
  action:
  - data_template:
      entity_id: light.linear_pd300z2_plugin_dimmer_module_level
      brightness: "{{ trigger.payload | int }}"
    service_template: >
      {% if trigger.payload | int == 0 %}
        light.turn_off
      {% else %} 
        light.turn_on     
      {% endif %}       

- id: linear_pd300z2_plugin_dimmer_module_level
  alias: linear_pd300z2_plugin_dimmer_module_level
  trigger:
  - platform: mqtt
    topic: "/HAwirelesslink/return/light/linear_pd300z2_plugin_dimmer_module_level/state"
  action:
  - data:
      entity_id: light.linear_pd300z2_plugin_dimmer_module_level
    service_template: >
      {% if trigger.payload == 'on' %}
        light.turn_on
      {% else %} 
        light.turn_off      
      {% endif %}


- id: livingroom_entry_brightness
  alias: livingroom_entry_brightness
  trigger:
  - platform: mqtt
    topic: "/HAwirelesslink/return/light/livingroom_entry/brightness"
  action:
  - data_template:
      entity_id: light.livingroom_entry
      brightness: "{{ trigger.payload | int }}"
    service_template: >
      {% if trigger.payload | int == 0 %}
        light.turn_off
      {% else %} 
        light.turn_on     
      {% endif %}       

- id: livingroom_entry
  alias: livingroom_entry
  trigger:
  - platform: mqtt
    topic: "/HAwirelesslink/return/light/livingroom_entry/state"
  action:
  - data:
      entity_id: light.livingroom_entry
    service_template: >
      {% if trigger.payload == 'on' %}
        light.turn_on
      {% else %} 
        light.turn_off      
      {% endif %}

- id: main_bath_vent_light_brightness
  alias: main_bath_vent_light_brightness
  trigger:
  - platform: mqtt
    topic: "/HAwirelesslink/return/light/main_bath_vent_light/brightness"
  action:
  - data_template:
      entity_id: light.main_bath_vent_light
      brightness: "{{ trigger.payload | int }}"
    service_template: >
      {% if trigger.payload | int == 0 %}
        light.turn_off
      {% else %} 
        light.turn_on     
      {% endif %}       

- id: main_bath_vent_light
  alias: main_bath_vent_light
  trigger:
  - platform: mqtt
    topic: "/HAwirelesslink/return/light/main_bath_vent_light/state"
  action:
  - data:
      entity_id: light.main_bath_vent_light
    service_template: >
      {% if trigger.payload == 'on' %}
        light.turn_on
      {% else %} 
        light.turn_off      
      {% endif %}
      
- id: main_bath_fan
  alias: main_bath_fan
  trigger:
  - platform: mqtt
    topic: "/HAwirelesslink/return/switch/main_bath_fan/state"
  action:
  - data:
      entity_id: switch.main_bath_fan
    service_template: >
      {% if trigger.payload == 'on' %}
        switch.turn_on
      {% else %} 
        switch.turn_off      
      {% endif %}

- id: garage_outlet
  alias: garage_outlet
  trigger:
  - platform: mqtt
    topic: "/HAwirelesslink/return/switch/enerwave_zw15rm_plus_15a_tr_smart_meter_duplex_receptacle_switch/state"
  action:
  - data:
      entity_id: switch.enerwave_zw15rm_plus_15a_tr_smart_meter_duplex_receptacle_switch
    service_template: >
      {% if trigger.payload == 'on' %}
        switch.turn_on
      {% else %} 
        switch.turn_off      
      {% endif %}

- id: main_bath_vanity_brightness
  alias: main_bath_vanity_brightness
  trigger:
  - platform: mqtt
    topic: "/HAwirelesslink/return/light/leviton_dz6hd_1bz_decora_600w_smart_dimmer_level/brightness"
  action:
  - data_template:
      entity_id: light.leviton_dz6hd_1bz_decora_600w_smart_dimmer_level
      brightness: "{{ trigger.payload | int }}"
    service_template: >
      {% if trigger.payload | int == 0 %}
        light.turn_off
      {% else %} 
        light.turn_on     
      {% endif %}       

- id: main_bath_vanity_light
  alias: main_bath_vanity_light
  trigger:
  - platform: mqtt
    topic: "/HAwirelesslink/return/light/leviton_dz6hd_1bz_decora_600w_smart_dimmer_level/state"
  action:
  - data:
      entity_id: light.leviton_dz6hd_1bz_decora_600w_smart_dimmer_level
    service_template: >
      {% if trigger.payload == 'on' %}
        light.turn_on
      {% else %} 
        light.turn_off      
      {% endif %}
