- id: xmaslights
  alias: xmaslights
  trigger:
  - platform: mqtt
    topic: "/HAwirelesslink/return/switch/xmaslights/state"
  action:
  - data:
      entity_id: switch.xmaslights
    service_template: >
      {% if trigger.payload == 'on' %}
        switch.turn_on
      {% else %} 
        switch.turn_off      
      {% endif %}

- id: linear_pd300z2_plugin_dimmer_module_level_brightness
  alias: linear_pd300z2_plugin_dimmer_module_level_brightness
  trigger:
  - platform: mqtt
    topic: "/HAwirelesslink/return/light/linear_pd300z2_plugin_dimmer_module_level/brightness"
  action:
  - data:
      entity_id: light.linear_pd300z2_plugin_dimmer_module_level
      brightness: int(trigger.payload)
    service_template: >
      {% if int(trigger.payload) == 0 %}
        light.turn_off
      {% else %} 
        light.turn_on     
      {% endif %}

- id: linear_pd300z2_plugin_dimmer_module_level
  alias: linear_pd300z2_plugin_dimmer_module_level
  trigger:
  - platform: mqtt
    topic: "/HAwirelesslink/return/light/linear_pd300z2_plugin_dimmer_module_level/state"
  action:
  - data:
      entity_id: light.linear_pd300z2_plugin_dimmer_module_level
    service_template: >
      {% if trigger.payload == 'on' %}
        light.turn_on
      {% else %} 
        light.turn_off      
      {% endif %}
