homeassistant:
  # Name of the location where Home Assistant is running
  name: Wirelesslink
  # Location required to calculate the time the sun rises and sets
  latitude: 42.422097
  longitude: -83.772937
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 283
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  # Customization file
  customize: !include customize.yaml

# Enables the frontend
frontend:

discovery:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:

updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# View all events in a logbook
logbook:

# Cloud
cloud:

system_health:

speedtestdotnet:
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload

zwave:
  network_key: !secret ZWNK
  usb_path: /dev/ttyUSB0
  device_config: !include zwave_device_config.yaml

input_boolean:
  zigbee_permit_join:
    name: Allow devices to join
    initial: off
    icon: mdi:cellphone-wireless
    
timer:
  zigbee_permit_join:
    name: Time remaining
    duration: 600 # Updated this to the number of seconds you wish

# Enable connection to MQTT server
mqtt:
  broker: 192.168.1.243
  username: firemogle
  password: !secret MQTTPW
  discovery: false
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

mqtt_statestream:
  base_topic: hawirelesslink
  publish_attributes: true
  publish_timestamps: true
  include:
    domains:
      - switch
      - light
      - sensor
      
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include_dir_merge_list sensors/

