homeassistant:
  # Name of the location where Home Assistant is running
  name: Wirelesslink
  # Location required to calculate the time the sun rises and sets
  latitude: 42.422097
  longitude: -83.772937
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 283
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  # Customization file
  customize: !include customize.yaml

# Enables the frontend
frontend:

#discovery:
#zeroconf:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:

updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# View all events in a logbook
#logbook:

# Cloud
cloud:

system_health:

light:
  - platform: decora_wifi
    username: !secret DECORA_USER
    password: !secret DECORA_PW
  
  - platform: group
    name: hall_lights
    entities:
      - light.hallway
      - light.leviton_dz6hd_1bz_decora_600w_smart_dimmer_level_3

speedtestdotnet:
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload

zwave:
  network_key: "0x05, 0x3C, 0xB9, 0x02, 0x36, 0x8E, 0x6E, 0x68, 0xBD, 0xE2, 0x9C, 0xFE, 0xEA, 0x98, 0x82, 0xCE"
  usb_path: /dev/ttyUSB0
  device_config: !include zwave_device_config.yaml
  
# Try ZHA with supposed fixes  
zha:
  usb_path: /dev/ttyUSB1
  database_path: /config/zigbee.db
  device_config:
      00:22:a3:00:00:16:d0:39-1:
          type: 'light'
      00:22:a3:00:00:20:d3:9d-1:
          type: 'light'

# Enable connection to MQTT server
mqtt:
  broker: 192.168.2.2
  username: firemogle
  password: firemogleHA
  discovery: false
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

mqtt_statestream:
  base_topic: hawirelesslink
  publish_attributes: true
  publish_timestamps: true
  include:
    domains:
      - switch
      - light
      - sensor
      - binary_sensor
      - fan
      - lock
      
group: !include groups.yaml
automation: !include_dir_merge_list automations/
script: !include scripts.yaml
sensor: !include_dir_merge_list sensors/

