- platform: systemmonitor
  resources:
    - type: memory_free
    - type: processor_use
    - type: swap_use_percent
    - type: last_boot
    - type: disk_use_percent
      arg: /home

- platform: mqtt
  name: Bridge state
  state_topic: "zigbee2mqtt/bridge/state
  icon: mdi:router-wireless
