- alias: "MQTT Light Color"
  trigger:
    - platform: mqtt
      topic: '/HAwirelesslink/return/light/#'
  condition:
  - condition: template
    value_template:  "{{ trigger.topic.split('/')[5] == 'rgb_color' }}"
  action:
    - service: light.turn_on
      data_template:
        entity_id: "{{ trigger.topic.split('/')[3] }}.{{ trigger.topic.split('/')[4] }}"
        rgb_color:
          - "{{ trigger.payload[:2] | int(0,16) }}"
          - "{{ trigger.payload[2:-2] | int(0,16) }}"
          - "{{ trigger.payload[-2:] | int(0,16) }}"
