- alias: sync_hall
  trigger:
    - platform: state
      entity_id: light.hallway
    - platform: state
      entity_id: light.leviton_dz6hd_1bz_decora_600w_smart_dimmer_level_3
    - platform: state
      entity_id: light.hall_lights
  action:

    sequence:
      - service_template: >
          {% if is_state('trigger.to_state.state', 'off') %}
            light.turn_off
          {% else %}
            light.turn_on
          {% endif %}
        data_template:
          entity_id: light.leviton_dz6hd_1bz_decora_600w_smart_dimmer_level_3
          brightness: >
            "{{ trigger.to_state.attributes.brightness }}"
      - service_template: >
          {% if is_state('trigger.to_state.state', 'off') %}
            light.turn_off
          {% else %}
            light.turn_on
          {% endif %}
        data_template:
          entity_id: light.hall_lights
          brightness: >
            "{{ trigger.to_state.attributes.brightness }}"
      - service_template: >
          {% if is_state('trigger.to_state.state', 'off') %}
            light.turn_off
          {% else %}
            light.turn_on
          {% endif %}
        data_template:
          entity_id: light.hallway
          brightness: >
            "{{ trigger.to_state.attributes.brightness }}"
      - delay:
          milliseconds: 500

