- alias: Sync Hallway
  trigger:
    - platform: state
      entity_id: light.hall_lights
    - platform: state
      entity_id: light.hallway
    - platform: state
      entity_id: light.leviton_dz6hd_1bz_decora_600w_smart_dimmer_level_3

  action:
    service: light.turn_on
    data_template:
      entity_id: >
        {% if states('sensor.hall_lights_sync').split(',') == light.hall_lights  %}
          {{ light.hallway }}
        {% elif states('sensor.hall_lights_sync').split(',') == light.hallway %}
          {{ light.leviton_dz6hd_1bz_decora_600w_smart_dimmer_level_3 }}
        {% else %}
          {{ light.hall_lights }}
        {% endif %}
      brightness: >
        {{ (states('sensor.hall_lights_sync').split(',')).brightness | int }}
        
    service: light.turn_on
    data_template:
      entity_id: >
        {% if states('sensor.hall_lights_sync').split(',') == light.hall_lights  %}
          {{ light.leviton_dz6hd_1bz_decora_600w_smart_dimmer_level_3 }}
        {% elif states('sensor.hall_lights_sync').split(',') == light.hallway %}
          {{ light.hall_lights }}
        {% else %}
          {{ light.hallway }}
        {% endif %}
      brightness: >
        {{{ (states('sensor.hall_lights_sync').split(',')).brightness | int }}

