- alias: sync_hall
  trigger:
    - platform: state
      entity_id: light.hallway
    - platform: state
      entity_id: light.leviton_dz6hd_1bz_decora_600w_smart_dimmer_level_3
    - platform: state
      entity_id: light.hall_lights
  action:
      - choose:
        - conditions:
            - condition: template
              value_template: "{{ state_attr(trigger.entity_id, 'friendly_name') == states.light.hallway.friendly_name }}" 
          sequence:
            - alias: "Hallway light pressed; loop until everything matches"
            - service_template: >
                {% if is_state('light.hallway', 'off') %}
                  light.turn_off
                {% else %}
                  light.turn_on
                {% endif %}
              data_template:
                entity_id: light.leviton_dz6hd_1bz_decora_600w_smart_dimmer_level_3
                brightness: >
                  "{{ trigger.to_state.attributes.brightness }}"
            - service_template: >
                {% if is_state('light.hallway', 'off') %}
                  light.turn_off
                {% else %}
                  light.turn_on
                {% endif %}
              data_template:
                entity_id: light.hall_lights
                brightness: >
                  "{{ trigger.to_state.attributes.brightness }}"
            - delay:
                milliseconds: 500

        - conditions:
            - condition: template
              value_template: "{{ state_attr(trigger.entity_id, 'friendly_name') == states.light.leviton_dz6hd_1bz_decora_600w_smart_dimmer_level_3.friendly_name }}" 
          sequence:
            - alias: "2nd hall light pressed; loop until everything matches"
              sequence:
              - service_template: >
                  {% if is_state('light.leviton_dz6hd_1bz_decora_600w_smart_dimmer_level_3', 'off') %}
                    light.turn_off
                  {% else %}
                    light.turn_on
                  {% endif %}
                data_template:
                  entity_id: light.hallway
                  brightness: >
                    "{{ trigger.to_state.attributes.brightness }}"
              - service_template: >
                  {% if is_state('light.leviton_dz6hd_1bz_decora_600w_smart_dimmer_level_3', 'off') %}
                    light.turn_off
                  {% else %}
                    light.turn_on
                  {% endif %}
                data_template:
                  entity_id: light.hall_lights
                  brightness: >
                    "{{ trigger.to_state.attributes.brightness }}"
              - delay:
                  milliseconds: 500

        - conditions:
            - condition: template
              value_template: "{{ state_attr(trigger.entity_id, 'friendly_name') == states.light.hall_lights.friendly_name }}" 
          sequence:
            - alias: "Lights changed in HA; loop until everything matches"
              sequence:
              - service_template: >
                  {% if is_state('light.hall_lights', 'off') %}
                    light.turn_off
                  {% else %}
                    light.turn_on
                  {% endif %}
                data_template:
                  entity_id: light.hallway
                  brightness: >
                    "{{ trigger.to_state.attributes.brightness }}"
              - service_template: >
                  {% if is_state('light.hall_lights', 'off') %}
                    light.turn_off
                  {% else %}
                    light.turn_on
                  {% endif %}
                data_template:
                  entity_id: light.leviton_dz6hd_1bz_decora_600w_smart_dimmer_level_3
                  brightness: >
                    "{{ trigger.to_state.attributes.brightness }}"
              - delay:
                  milliseconds: 500
