- alias: sync_hall
  trigger:
    - platform: state
      entity_id: light.hallway
    - platform: state
      entity_id: light.leviton_dz6hd_1bz_decora_600w_smart_dimmer_level_3
    - platform: state
      entity_id: light.hall_lights
  condition:
    - condition: state
      entity_id: 'input_text.hall_light_initialize'
      state: 'none'
  action:
    - service: input_text.set_value
      data_template:
        entity_id: input_text.hall_light_initialize
        value: '{{ trigger.to_state.name }}'
