- id: main_inst_automation
  alias: main_inst_automation
  initial_state: 'off'
  trigger:
  - platform: mqtt
    topic: "HAMaster/status"
  action:
  - data:
      entity_id: "all"
    service_template: >
      {% if trigger.payload == 'online' %}
        automation.turn_on
      {% else %} 
        automation.turn_off
      {% endif %}
  - data:
      entity_id: "main_inst_automation"
    service:
      automation.turn_on
