- alias: sync_hall_light
  trigger:
    - platform: state
      entity_id: light.hallway
    - platform: state
      entity_id: light.leviton_dz6hd_1bz_decora_600w_smart_dimmer_level_3
    - platform: state
      entity_id: light.hall_lights
  condition:
    condition: or
    conditions:
      - condition: template
        value_template: "{{ states('input_text.hall_light_initialize') = 'hallway' }}"
      - condition: template
        value_template: "{{ states('input_text.hall_light_initialize') = 'leviton_dz6hd_1bz_decora_600w_smart_dimmer_level_3' }}"
      - condition: template
        value_template: "{{ states('input_text.hall_light_initialize') = 'hall_lights' }}"
  action:
    - service: light.turn_on
      data_template:
        entity_id: >
             {% if is_state('input_text.hall_light_initialize', 'hallway') %}
               light.hall_lights
             {% else if is_state('input_text.hall_light_initialize', 'leviton_dz6hd_1bz_decora_600w_smart_dimmer_level_3') %}
               light.hall_lights
             {% else %}
               light.hallway
             {% endif %} 
        brightness: "{{trigger.brightness}}"
    - service: light.turn_on
      data_template:
        entity_id: >
             {% if is_state('input_text.hall_light_initialize', 'hallway') %}
               light.leviton_dz6hd_1bz_decora_600w_smart_dimmer_level_3
             {% else if is_state('input_text.hall_light_initialize', 'leviton_dz6hd_1bz_decora_600w_smart_dimmer_level_3') %}
               light.hallway
             {% else %}
               light.leviton_dz6hd_1bz_decora_600w_smart_dimmer_level_3
             {% endif %} 
        brightness: "{{trigger.brightness}}"
